### ISSUE TITLE
Cannot create basic starting files set for gen2 shells

### ISSUE THREAD

**Issue by jimbr70** [QualiSystems/shellfoundry#155]
### Issue details
Shellfoundry fails when attempting gen2 shell create:
PS C:\Python27\shells> ..\Scripts\shellfoundry.exe new gen2\resource-shell
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\shellfoundry.exe\__main__.py", line 9, in <module>
  File "c:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\Python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\Python27\lib\site-packages\shellfoundry\bootstrap.py", line 56, in new
    NewCommandExecutor().new(name, template, version)
  File "c:\Python27\lib\site-packages\shellfoundry\commands\new_command.py", line 37, in new
    self._import_online_template(name, running_on_same_folder, template, version)
  File "c:\Python27\lib\site-packages\shellfoundry\commands\new_command.py", line 63, in _import_online_template
    running_on_same_folder)
  File "c:\Python27\lib\site-packages\shellfoundry\utilities\cookiecutter_integration.py", line 19, in compile_template
    overwrite_if_exists=False, output_dir=output_dir)
  File "c:\Python27\lib\site-packages\cookiecutter\main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "c:\Python27\lib\site-packages\cookiecutter\generate.py", line 349, in generate_files
    generate_file(project_dir, infile, context, env)
  File "c:\Python27\lib\site-packages\cookiecutter\generate.py", line 176, in generate_file
    with io.open(outfile, 'w', encoding='utf-8') as fh:
IOError: [Errno 2] No such file or directory: u'C:\\Python27\\shells\\gen2\\resource-shell\\tests\\test_gen2\\resource-s
hell.py'
PS C:\Python27\shells> dir .\gen2\resource-shell\tests\
PS C:\Python27\shells> NO FILES FOUND

So what else post this error do I not have?

### Steps to reproduce

see above

### Affected platforms

- [X ] Windows
- [? ] Linux

_Please fill additional environment specific configuration_
Running from Windows 10 laptop

**Comment by jimbr70** [comment]
In addition, the driver.py OB has an error:

class Gen2/ResourceShellDriver (ResourceDriverInterface):

The above line generates colon expected.  Guessing Gen2/ needs to be removed.

**Comment by kalsky** [comment]
Hi Jim
Your command is wrong, it should be:
shellfoundry new myshell --template gen2/resource

The issue here might be to better handle wrong inputs..

**Comment by GalcQuali** [comment]
No Issue.
