### ISSUE TITLE
Errors with python3

### ISSUE THREAD

**Issue by sadanandhegde** [QualiSystems/shellfoundry#241]
### Issue details
I am seeing these errors 
•	Shellfoundry list fails (something to do about password)
•	Shellfoundry config password fails

### Steps to reproduce
Create a python 3.7 env, install shellfoundry (1.2.12) , then try the following commands 
* shellfoundry config password admin
OR
* shellfoundry new tst_resource --template=gen2/resource

### Affected version:
1.2.12

### Affected platforms
- [Y] Windows

Here is the output

```
PS C:\Python37\venv_tst> .\scripts\activate
(venv_tst) PS C:\Python37\venv_tst> .\Scripts\shellfoundry.exe config
Key                Value
-----------------------------------
domain             Global
password           [encrypted]
username           admin
port               9000         *
host               localhost
author             sadanand.h
online_mode        True
template_location  Empty        *
github_login                    *
github_password    [encrypted]  *
defaultview        gen2
user               admin

* Value marked with '*' is actually the default value and has not been override by the user.
(venv_tst) PS C:\Python37\venv_tst> .\Scripts\shellfoundry.exe config password admin
Failed to save key value
(venv_tst) PS C:\Python37\venv_tst> .\Scripts\shellfoundry.exe config username admin
username: admin was saved successfully
(venv_tst) PS C:\Python37\venv_tst> .\Scripts\shellfoundry.exe config password admin
Failed to save key value
(venv_tst) PS C:\Python37\venv_tst> .\Scripts\shellfoundry.exe list
Traceback (most recent call last):
  File "c:\users\sadanand.h\appdata\local\programs\python\python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sadanand.h\appdata\local\programs\python\python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\venv_tst\Scripts\shellfoundry.exe\__main__.py", line 7, in <module>
  File "c:\python37\venv_tst\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python37\venv_tst\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python37\venv_tst\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\venv_tst\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python37\venv_tst\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\decorators\version_check.py", line 21, in decorator
    if self.cloudshell_config_reader.read().online_mode.lower() == "true":
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\utilities\config_reader.py", line 56, in read
    return self.reader.read_from_config(config[INSTALL])
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\utilities\config_reader.py", line 105, in read_from_config
    github_login, github_password)
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\models\install_config.py", line 22, in __init__
    self.password = self._decode_password(password)
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\models\install_config.py", line 58, in _decode_password
    return pass_mod.normalize(password)
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\utilities\modifiers\configuration\password_modification.py", line 29, in normalize
    decoded = self._decode_encode(base64.decodebytes(value.encode()), encryption_key)
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\utilities\modifiers\configuration\password_modification.py", line 46, in _decode_encode
    return ''.join(chr(ord(source) ^ ord(key)) for source, key in zip(value, key * 100))
  File "c:\python37\venv_tst\lib\site-packages\shellfoundry\utilities\modifiers\configuration\password_modification.py", line 46, in <genexpr>
    return ''.join(chr(ord(source) ^ ord(key)) for source, key in zip(value, key * 100))
TypeError: ord() expected string of length 1, but int found
(venv_tst) PS C:\Python37\venv_tst>


(venv_tst) PS C:\Python37\venv_tst> .\Scripts\shellfoundry.exe version
shellfoundry version 1.2.12
(venv_tst) PS C:\Python37\venv_tst>
```

**Comment by Costya-Y** [comment]
Fixed and released
