### ISSUE TITLE
Install fails to import package created using merged package

### ISSUE THREAD

**Issue by borismod** [QualiSystems/shellfoundry#40]
### Issue details

Install fails to import package created using merged package

### Steps to reproduce

```bash
shellfoundry new bezeq-router --template networking/router
cd bezeq-router
shellfoundry install
```

<details>
 <summary>Error message</summary>
C:\work\GitHub\bezeq_router> shellfoundry install
shellfoundry - CloudShell shell command-line tool
Shell package was successfully created:
C:\work\GitHub\bezeq_router\dist\bezeq-router.zip
Installing package C:\work\GitHub\bezeq_router\dist\bezeq-router.zip into CloudShell at http://localhost:9000
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\shellfoundry.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\shellfoundry\bootstrap.py", line 56, in install
    InstallCommandExecutor().install()
  File "c:\python27\lib\site-packages\shellfoundry\commands\install_command.py", line 18, in install
    self.installer.install(shell_config.name, cloudshell_config)
  File "c:\python27\lib\site-packages\shellfoundry\utilities\installer.py", line 25, in install
    server.upload_environment_zip_file(package_full_path)
  File "c:\python27\lib\site-packages\qpm\packaging\quali_api_client.py", line 93, in upload_environment_zip_file
    self.upload_environment_zip_data(zipdata)
  File "c:\python27\lib\site-packages\qpm\packaging\quali_api_client.py", line 151, in upload_environment_zip_data
    raise Exception('Error uploading Quali API zip package: '+o['ErrorMessage'])
Exception: Error uploading Quali API zip package: Failed to import datamodel. Driver 'Generic Cisco IOS
Driver Version2' not found
</details>

### Affected version:
0.0.29

### Affected platforms

- [x] Windows
- [x] Linux

**Comment by doppleware** [comment]
This is closed
