### ISSUE TITLE
Allow shellfoundry to work behind proxy

### ISSUE THREAD

**Issue by ric79** [QualiSystems/shellfoundry#44]
### Enhancement details
As a user of shellfoundry I want to be able to use _list_ and _new_ commands behind proxy.

## Background
_shellfoundry list_ command retrieves templates from https://github.com/QualiSystems/shellfoundry/blob/master/templates.yml

## Task
Add --proxy flag that enables to specify address of proxy server

Repro step(s):

```bash
shellfoundry list
```

<details> 
<summary>Console error message</summary>

shellfoundry - CloudShell shell command-line tool
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\shellfoundry.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\shellfoundry\bootstrap.py", line 29, in list
    ListCommandExecutor().list()
  File "c:\python27\lib\site-packages\shellfoundry\commands\list_command.py", line 11, in list
    templates = self.template_retriever.get_templates()
  File "c:\python27\lib\site-packages\shellfoundry\utilities\template_retriever.py", line 14, in get_templates
    response = self._get_templates_from_github()
  File "c:\python27\lib\site-packages\shellfoundry\utilities\template_retriever.py", line 26, in _get_templates_from_github
    return requests.get(TEMPLATES_YML).text
  File "c:\python27\lib\site-packages\requests\api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "c:\python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.github.com', port=443): Max retries exceeded with url: /QualiSystems/shellfoundry/master/templates.yml (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000038F0208>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

</details>

**Comment by ric79** [comment]
Hello, 
just to clarify that I have no direct access to github but I need to specify the company proxy

**Comment by doppleware** [comment]
Hi Ricardo, 
Can you try again with the latest version?
If it doesn't work, you can try setting the following env variables before running ShellFoundry:

$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"

Thanks!
Roni

**Comment by ric79** [comment]
It still gives me an error...

```
C:\Python27\Scripts>pip install shellfoundry --proxy $HTTP_PROXY

C:\Python27\Scripts>set HTTP_PROXY="http://USERNAME:PASSWORD@IP:PORT"

C:\Python27\Scripts>set HTTPS_PROXY="http://USERNAME:PASSWORD@IP:PORT"

C:\Python27\Scripts>pip install shellfoundry --proxy $HTTP_PROXY

C:\Python27\Scripts>shellfoundry list
shellfoundry - CloudShell shell command-line tool
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\shellfoundry.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\shellfoundry\bootstrap.py", line 29, in list
    ListCommandExecutor().list()
  File "c:\python27\lib\site-packages\shellfoundry\commands\list_command.py", line 11, in list
    templates = self.template_retriever.get_templates()
  File "c:\python27\lib\site-packages\shellfoundry\utilities\template_retriever.py", line 14, in get_templates
    response = self._get_templates_from_github()
  File "c:\python27\lib\site-packages\shellfoundry\utilities\template_retriever.py", line 26, in _get_templates_from_github
    return requests.get(TEMPLATES_YML).text
  File "c:\python27\lib\site-packages\requests\api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "c:\python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 465, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='raw.github.com', port=443): Max retries exceeded with url: /QualiSystems/shellfoundry/master/templates.yml (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000038B83C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)))

C:\Python27\Scripts>
```
