### ISSUE TITLE
shellfoundry install fails when name has underline in it

### ISSUE THREAD

**Issue by borismod** [QualiSystems/shellfoundry#82]
### Issue details

bug:

you get the following error message:

Missing artifact not added to shell package: ShalomHaverDriver.zip
Adding artifact to shell package: shell-icon.png
Shell package was successfully created: dist\Shalom_Haver.zip
Connecting to CloudShell localhost
Updating shell C:\Work\shell entity\shalom_haver\dist\Shalom_Haver.zip
Shell not found, adding shell C:\Work\shell entity\shalom_haver\dist\Shalom_Haver.zip
Traceback (most recent call last):
  File "C:\Python27\Scripts\shellfoundry-script.py", line 9, in <module>
    load_entry_point('shellfoundry==0.0.35', 'console_scripts', 'shellfoundry')()
  File "c:\python27\lib\site-packages\click\core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "c:\python27\lib\site-packages\shellfoundry\bootstrap.py", line 65, in install
    InstallCommandExecutor().install()
  File "c:\python27\lib\site-packages\shellfoundry\commands\install_command.py", line 23, in install
    self.shell_package_installer.install(current_path)
  File "c:\python27\lib\site-packages\shellfoundry\utilities\shell_package_installer.py", line 34, in install
    client.add_shell(package_full_path)
  File "c:\python27\lib\site-packages\cloudshell\rest\api.py", line 48, in add_shell
    raise Exception(response.text)
Exception: {"Message":"Error: Artifact 'ShalomHaverDriver.zip' not found in Cloud Service Archive."}
### Steps to reproduce

run the following commands:
1. shellfoundry new shalom_haver --template tosca/networking/switch
2. cd shalom_haver
3. shellfoundry install
### Affected version:

 0.0.36
### Affected platforms
- [x] Windows
- [x] Linux

Python 2.7.10

**Comment by borismod** [comment]
Fixed
